version: '2'

services:
  microtransactionsupdater:
    container_name: microtransactionsupdater
    image: petprojects/micro-transactions-updater:${BUILD_VERSION}
    network_mode: bridge
    environment:
      - 'MTS_APP_SETTINGS_ConsulStoreConfiguration:Environment=${CONSUL_ENVIRONMENT}'
      - 'MTS_APP_SETTINGS_ConsulClientConfiguration:Address=${CONSUL_ADDRESS}'
    build:
      context: ./src/Presentation.ConsoleApplication
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
