version: '2'

services:
  microtransactionsupdater:
    container_name: microtransactionsupdater
    image: petprojects/micro-transactions-updater:${BUILD_VERSION}
    network_mode: bridge
    build:
      context: ./src/Presentation.ConsoleApplication
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
